using AgenciesManagement;
using System;
using System.Data;
using System.Windows.Forms;

namespace Kierownik_Magazynów.AgenciesManagement
{
    public partial class RangeAdder : Form
    {
        AgencyManagementDataService dataService;

        public RangeAdder(DataTable agencies, DataTable warehouses, ref AgencyManagementDataService agencyManagementDataService)
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            lookUpEditAgencies.Properties.DataSource = agencies;
            // This line of code is generated by Data Source Configuration Wizard
            lookUpEditWarehouse.Properties.DataSource = warehouses;

            this.dataService = agencyManagementDataService;
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            dataService.AddRange((int)this.lookUpEditWarehouse.EditValue, (int)this.lookUpEditAgencies.EditValue, Int16.Parse(this.textEditFrom.Text),Int16.Parse(this.textEditTo.Text));
            this.Close();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
