//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kierownik_Magazynów.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Range
    {
        public int RangeId { get; set; }
        public int WarehouseId { get; set; }
        public int AgencyId { get; set; }
        public int RangeFrom { get; set; }
        public int RangeTo { get; set; }
        public int TotalRange { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
